package ULDE::Web::Model::DB::ULDE;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

#__PACKAGE__->config(
#    schema_class => 'ULDE::Schema::ULDE',
    
#    connect_info => {
#        dsn => 'dbi:Pg:dbname=ulde.db',
#        user => 'ulde',
#        password => '',
#    }
#);

=head1 NAME

ULDE::Web::Model::DB::ULDE - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<ULDE::Web>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<ULDE::Schema::ULDE>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
